Repository buttplugio/buttplug-csharp, pull requests merged in 2018-03, with the labels that each got.

#356 build: Move all non-.Net Standard project to .Net Framework 4.7
  Buttplug.Apps.DeviceSimulatorGUI/App.config
  Buttplug.Apps.DeviceSimulatorGUI/Buttplug.Apps.DeviceSimulatorGUI.csproj
  Buttplug.Apps.DeviceSimulatorGUI/Properties/Resources.Designer.cs
  Buttplug.Apps.DeviceSimulatorGUI/Properties/Settings.Designer.cs
  Buttplug.Apps.ExampleClientGUI/App.config
  Buttplug.Apps.ExampleClientGUI/Buttplug.Apps.ExampleClientGUI.csproj
  Buttplug.Apps.ExampleClientGUI/Properties/Resources.Designer.cs
  Buttplug.Apps.ExampleClientGUI/Properties/Settings.Designer.cs
  Buttplug.Apps.GameVibrationRouter.GUI/App.config
  Buttplug.Apps.GameVibrationRouter.GUI/Buttplug.Apps.GameVibrationRouter.GUI.csproj
  Buttplug.Apps.GameVibrationRouter.GUI/Properties/Settings.Designer.cs
  Buttplug.Apps.GameVibrationRouter.Interface/Buttplug.Apps.GameVibrationRouter.Interface.csproj
  Buttplug.Apps.GameVibrationRouter.Payload/Buttplug.Apps.GameVibrationRouter.Payload.csproj
  Buttplug.Apps.KiirooEmulatorGUI.Test/Buttplug.Apps.KiirooEmulatorGUI.Test.csproj
  Buttplug.Apps.KiirooEmulatorGUI.Test/app.config
  Buttplug.Apps.KiirooEmulatorGUI/App.config
  Buttplug.Apps.KiirooEmulatorGUI/Buttplug.Apps.KiirooEmulatorGUI.csproj
  Buttplug.Apps.KiirooEmulatorGUI/Properties/Resources.Designer.cs
  Buttplug.Apps.KiirooEmulatorGUI/Properties/Settings.Designer.cs
  Buttplug.Apps.KiirooEmulatorGUI/packages.config
  Buttplug.Apps.WebsocketServerGUI.Test/Buttplug.Apps.WebsocketServerGUI.Test.csproj
  Buttplug.Apps.WebsocketServerGUI.Test/app.config
  Buttplug.Apps.WebsocketServerGUI/App.config
  Buttplug.Apps.WebsocketServerGUI/Buttplug.Apps.WebsocketServerGUI.csproj
  Buttplug.Apps.WebsocketServerGUI/Properties/Resources.Designer.cs
  Buttplug.Apps.WebsocketServerGUI/Properties/Settings.Designer.cs
  Buttplug.Client.Test/Buttplug.Client.Test.csproj
  Buttplug.Client.Test/app.config
  Buttplug.Components.Controls/Buttplug.Components.Controls.csproj
  Buttplug.Components.Controls/Properties/Resources.Designer.cs
  Buttplug.Components.Controls/Properties/Settings.Designer.cs
  Buttplug.Components.Controls/app.config
  Buttplug.Components.KiirooPlatformEmulator/Buttplug.Components.KiirooPlatformEmulator.csproj
  Buttplug.Components.KiirooPlatformEmulator/app.config
  Buttplug.Components.WebsocketServer/Buttplug.Components.WebsocketServer.csproj
  Buttplug.Components.WebsocketServer/app.config
  Buttplug.Server.Managers.ErosTek/Buttplug.Server.Managers.ETSerialManager.csproj
  Buttplug.Server.Managers.SimulatorManager/Buttplug.Server.Managers.SimulatorManager.csproj
  Buttplug.Server.Managers.SimulatorManager/app.config
  Buttplug.Server.Managers.UWPBluetoothManager/Buttplug.Server.Managers.UWPBluetoothManager.csproj
  Buttplug.Server.Managers.UWPBluetoothManager/app.config
  Buttplug.Server.Managers.XInputGamepadManager/Buttplug.Server.Managers.XInputGamepadManager.csproj
  Buttplug.Server.Managers.XInputGamepadManager/app.config
  Buttplug.Server.Test/Buttplug.Server.Test.csproj
  Buttplug.Server.Test/app.config
Labels: applications, build

#357 Adding support for individual vibrator control in dual motor WeVibes
  Buttplug.Server.Test/Bluetooth/Devices/WeVibeTests.cs
  Buttplug.Server/Bluetooth/Devices/KiirooGen2Vibe.cs
  Buttplug.Server/Bluetooth/Devices/WeVibe.cs
Labels: toy support

#361 Add WinUSB Manager and Rez TranceVibrator support
  Buttplug.Components.Controls/Buttplug.Components.Controls.csproj
  Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
  Buttplug.Server.Managers.WinUSBManager/Buttplug.Server.Managers.WinUSBManager.csproj
  Buttplug.Server.Managers.WinUSBManager/Properties/AssemblyInfo.cs
  Buttplug.Server.Managers.WinUSBManager/RezTranceVibratorDevice.cs
  Buttplug.Server.Managers.WinUSBManager/WinUSBManager.cs
  Buttplug.Server.Managers.WinUSBManager/app.config
  Buttplug.Server.Managers.WinUSBManager/packages.config
  Buttplug.sln
Labels: library, toy support

#369 feat: Cyclone X10 support
  Buttplug.Components.Controls/Buttplug.Components.Controls.csproj
  Buttplug.Components.Controls/ButtplugTabControl.xaml.cs
  Buttplug.Server.Managers.HidManager/Buttplug.Server.Managers.HidManager.csproj
  Buttplug.Server.Managers.HidManager/Devices/CycloneX10.cs
  Buttplug.Server.Managers.HidManager/HidButtplugDevice.cs
  Buttplug.Server.Managers.HidManager/HidDeviceFactory.cs
  Buttplug.Server.Managers.HidManager/HidManager.cs
  Buttplug.Server.Managers.HidManager/IHidDeviceInfo.cs
  Buttplug.Server.Managers.HidManager/Properties/AssemblyInfo.cs
  Buttplug.Server.Managers.HidManager/app.config
  Buttplug.Server.Managers.HidManager/packages.config
  Buttplug.sln
Labels: toy support
